--SIEMPRE QUE SE REALIZE ALGUN UPDATE SIEMPRE TIENE QUE A VER UN WHERE
--PARA NO COMETER EL ERROR DE ASIGNAR UN VALOR ERRONEO A TODOS LOS REGISTROS
UPDATE users SET age = '12' WHERE user_id = 4;

UPDATE users SET age = '20', init_date = '2005-05-05' WHERE user_id = 3;

