--OBTIENE UN VALOR MAXIMO Y NORMALMENTE SE RECOMIENDA UTILIZAR ESTA ESTRUCTURA
--DONDE SOLO SE CONSULTE EXPECIFICAMENTE EL VALOR DESEADO
SELECT MAX(age) FROM users;

--OBTIENE EL VALOR MINIMO
SELECT MIN(age) FROM users;

--CUANDO SE UTILIZA MIN O MAX NO SE RECOMIENDA AGREGAR MAS COLUMNAS EJEMPLO:
SELECT MAX(age), name FROM users;