--LA FUNCION COUNT CUENTA EL NUMERO DE REEGISTROS O EL VALOR QUE QUEREMOS CONTABILIZAR
SELECT COUNT(age) name FROM users;

--CUENTA EL NUMERO DE USUARIOS QUE SU EDAD ES MAYOR A 30
SELECT COUNT(*) FROM USERS WHERE AGE >= 30;