--CON EL ALIAS CREAMOS UNA COLUMNA CON EL NOMBRE DE UN ALIAS 
SELECT name, init_date FROM users WHERE age BETWEEN 20 AND 30;

--CON EL ALIAS SE PUEDE CAMBIAR EL NOMBRE DE NUESTRA COLUMNA
SELECT name, INIT_DATE AS 'Fecha de Inicio' FROM users WHERE age BETWEEN 20 AND 30;

--SE PUEDE UTILIZAR TAMBIEN COMILLAS DOBLES
SELECT name, INIT_DATE AS "Fecha de Inicio" FROM users WHERE age BETWEEN 20 AND 30;