--AGRUPA LOS VALORES Y SOLO DEVUELVE LOS VALORES
SELECT MAX(age) FROM users GROUP BY age;
SELECT COUNT(age) FROM users GROUP BY age;
SELECT COUNT(age), age AS 'EDADES' FROM users WHERE age > 15 GROUP BY age ORDER BY age DESC;
