--LA CLAVE NO SE PUEDE UTILIAR EN GUNCIONES AGREGADAS
--HAEVING ES UNA LIMITACION SOBRE UNA MISMA COLUMNA AGREGADA 
--SELECT (FUNCION AGREGADA) FROM (HEAVING LIMITACION) (COLUMNA AGREGADA);
SELECT COUNT(age) FROM users HAVING COUNT(age)>8;