--OBTIENE LOS REGISTROS DONDE UN USUARIO NO AGREGO EMAIL Y EL VALOR QUEDO NULO
SELECT * FROM users WHERE email IS NULL;

--OBTIENE LOS REGISTROS DONDE LOS USUARIOS NO TIENEN UN VALOR NULO EN EMAIL
SELECT * FROM users WHERE email IS NOT NULL;