-- AGREGAR UNA NUEVA COLUMNA
ALTER TABLE persons8
ADD surname VARCHAR(50);

--CAMBIAR EL NOMBRE DE LA COLUMNA
ALTER TABLE persons8
RENAME COLUMN surname TO description;

--MODIFICAR LOS PARAMETROS DEL TIPO DE DATO
ALTER TABLE persons8
MODIFY COLUMN description VARCHAR(250);

-- BORRA LA COLUMNA DE UNA TABLA
ALTER TABLE persons8
DROP COLUMN description;

--MODIFICAR LA TABLA USUARIOS Y AGREGA UNA RESTRICCION PARA CREAR UNA
--LLAVE FORANEA 
ALTER TABLE users
ADD CONSTRAINT fk_companies
FOREIGN KEY (company_id) REFERENCES companies (company_id);
