-- DEVUELVE LAS CONCIDENCIAS ENTRE UNA TABLA A Y B
-- PERO A EXCECCION DE LA TABLA A DEVUELVE TODOS LOS REGISTROS AUN QUE NO TENGA UNA
--CONCIDENCIA EN LA TABLA B
SELECT name, dni_number
FROM users
LEFT JOIN dni
ON users.user_id = dni.user_id;

-- DEVUELVE TODOS LOS REGISTROS DE LA TABLA IZQUIERDA
-- EN ESTE CASO DEVUELVE TODOS LOS REGISTROS DE LA TABLA USERS
-- LOS REGISTROS QUE NO TENGAN RELACION CON LA TABLA DNI. EN LA TABLA DNI SE
-- AGREGAN VALORES NULOS
SELECT *
FROM users
LEFT JOIN dni
ON users.user_id = dni.user_id;

-- SE CONSULTO DE MANERA INVERSA LAS TABLAS TOMAR EN CUENTA QUE TABLA QUEREMOS
-- QUE MUESTRE TODOS LOS DATOS CON LEFT JOIN EN ESTE CASO SE MUESTRAN TODOS 
-- LOS REGISTROS DE LA DERECHA DE LA TABLA DNI
SELECT name, dni_number
FROM dni
RIGHT JOIN users
ON users.user_id = dni.user_id;
